// swift-tools-version:6.2
// Generated by _test_tools/test_publish_libraries.py. Do not edit by hand.
import PackageDescription

let package = Package(
    name: "moot-core",
    platforms: [
        .macOS(.v26),
        .iOS(.v26),
    ],
    products: [
        .library(name: "EngramLib", targets: ["EngramLib"]),
        .library(name: "IntellectusLib", targets: ["IntellectusLib"]),
        .library(name: "SubstrateKernel", targets: ["SubstrateKernel"]),
        .library(name: "SubstrateLib", targets: ["SubstrateLib"]),
        .library(name: "SubstrateML", targets: ["SubstrateML"]),
        .library(name: "SubstrateTypes", targets: ["SubstrateTypes"])
    ],
    dependencies: [

    ],
    targets: [
        .target(
            name: "EngramLib",
            dependencies: ["SubstrateTypes", "SubstrateKernel"],
            path: "packages/libs/EngramLib/Sources/EngramLib"
        ),
        .testTarget(
            name: "EngramLibTests",
            dependencies: ["EngramLib"],
            path: "packages/libs/EngramLib/Tests/EngramLibTests"
        ),
        .target(
            name: "IntellectusLib",
            path: "packages/libs/IntellectusLib/Sources/IntellectusLib"
        ),
        .testTarget(
            name: "IntellectusLibTests",
            dependencies: ["IntellectusLib"],
            path: "packages/libs/IntellectusLib/Tests/IntellectusLibTests"
        ),
        .target(
            name: "SubstrateKernel",
            dependencies: ["SubstrateTypes", "IntellectusLib"],
            path: "packages/libs/SubstrateKernel/Sources/SubstrateKernel"
        ),
        .testTarget(
            name: "SubstrateKernelTests",
            dependencies: ["SubstrateKernel", "SubstrateTypes", "IntellectusLib"],
            path: "packages/libs/SubstrateKernel/Tests/SubstrateKernelTests"
        ),
        .target(
            name: "SubstrateLib",
            dependencies: ["SubstrateTypes", "SubstrateKernel", "SubstrateML", "IntellectusLib"],
            path: "packages/libs/SubstrateLib/Sources/SubstrateLib"
        ),
        .testTarget(
            name: "SubstrateLibTests",
            dependencies: ["SubstrateLib", "SubstrateTypes", "SubstrateKernel", "SubstrateML", "IntellectusLib"],
            path: "packages/libs/SubstrateLib/Tests/SubstrateLibTests"
        ),
        .testTarget(
            name: "SubstrateLibConformanceTests",
            dependencies: ["SubstrateLib", "SubstrateTypes", "SubstrateKernel", "SubstrateML"],
            path: "packages/libs/SubstrateLib/Tests/SubstrateLibConformanceTests"
        ),
        .target(
            name: "SubstrateML",
            dependencies: ["SubstrateTypes", "SubstrateKernel", "IntellectusLib"],
            path: "packages/libs/SubstrateML/Sources/SubstrateML"
        ),
        .testTarget(
            name: "SubstrateMLTests",
            dependencies: ["SubstrateML", "SubstrateTypes", "SubstrateKernel", "IntellectusLib"],
            path: "packages/libs/SubstrateML/Tests/SubstrateMLTests"
        ),
        .target(
            name: "SubstrateTypes",
            path: "packages/libs/SubstrateTypes/Sources/SubstrateTypes"
        ),
        .testTarget(
            name: "SubstrateTypesTests",
            dependencies: ["SubstrateTypes"],
            path: "packages/libs/SubstrateTypes/Tests/SubstrateTypesTests"
        )
    ]
)
